# Generated by Django 3.2.9 on 2021-12-22 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaWebowa', '0002_pacjent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomiar',
            name='timestamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='plec',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mezczyzna'), (0, 'Kobieta')]),
        ),
    ]
